import functions

functions.add_extension(".exe", "exe")
functions.add_extension(".msi", "exe")
functions.add_extension(".jpg", "imagenes")
functions.add_extension(".png", "imagenes")
functions.add_extension(".pdf", "documentos")
functions.add_extension(".zip", "comprimidos")
functions.add_extension(".rar", "comprimidos")
functions.add_extension(".7z", "comprimidos")
functions.add_extension(".docx", "documentos")
functions.add_extension(".pptx", "presentaciones")

functions.add_extension(".mp4", "videos")
functions.add_extension(".jar", "java")
functions.add_extension(".html", "html")
functions.add_extension(".htm", "html")
functions.add_extension(".gif", "imagenes")
functions.add_extension(".iso", "imagenes_discos")
functions.add_extension(".class", "java")